import type { PlantItem } from "@/types/plant";

const now = new Date().toISOString();

export const plantSeedData: PlantItem[] = [
  {
    id: "p1",
    scanCode: "PV-PLANT-0001",
    name: "Alphonso Mango Tree",
    species: "Mangifera indica",
    category: "fruit_tree",
    variety: "Alphonso",
    ageMonths: 24,
    location: "Orchard A",
    quantityAvailable: 18,
    unit: "tree",
    status: "available",
    tags: ["mango", "premium", "sweet"],
    notes: "High demand in summer season.",
    createdAt: now,
    updatedAt: now,
    imageUrl: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p2",
    scanCode: "PV-PLANT-0002",
    name: "Kent Mango Sapling",
    species: "Mangifera indica",
    category: "fruit_tree",
    variety: "Kent",
    ageMonths: 8,
    location: "Greenhouse 1",
    quantityAvailable: 32,
    unit: "seedling",
    status: "available",
    tags: ["mango", "sapling"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p3",
    scanCode: "PV-PLANT-0003",
    name: "Tommy Atkins Mango",
    species: "Mangifera indica",
    category: "fruit_tree",
    variety: "Tommy Atkins",
    ageMonths: 14,
    location: "Orchard B",
    quantityAvailable: 0,
    unit: "tree",
    status: "unavailable",
    tags: ["mango", "export"],
    notes: "Temporarily unavailable due to pruning.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p4",
    scanCode: "PV-PLANT-0004",
    name: "Lemon Tree",
    species: "Citrus limon",
    category: "fruit_tree",
    ageMonths: 20,
    location: "Orchard C",
    quantityAvailable: 12,
    unit: "tree",
    status: "available",
    tags: ["citrus"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p5",
    scanCode: "PV-PLANT-0005",
    name: "Guava Tree",
    species: "Psidium guajava",
    category: "fruit_tree",
    ageMonths: 16,
    location: "Orchard A",
    quantityAvailable: 9,
    unit: "tree",
    status: "available",
    tags: ["fruit", "hardy"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p6",
    scanCode: "PV-PLANT-0006",
    name: "Rose Bush",
    species: "Rosa rubiginosa",
    category: "flower",
    location: "Plot 2",
    quantityAvailable: 20,
    unit: "pot",
    status: "available",
    tags: ["ornamental", "fragrant"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p7",
    scanCode: "PV-PLANT-0007",
    name: "Lavender Pot",
    species: "Lavandula",
    category: "herb",
    location: "Greenhouse 2",
    quantityAvailable: 14,
    unit: "pot",
    status: "available",
    tags: ["herb", "aromatic"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p8",
    scanCode: "PV-PLANT-0008",
    name: "Basil Seedlings",
    species: "Ocimum basilicum",
    category: "herb",
    location: "Nursery Bay",
    quantityAvailable: 45,
    unit: "seedling",
    status: "available",
    tags: ["kitchen", "seedling"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p9",
    scanCode: "PV-PLANT-0009",
    name: "Tomato Plant",
    species: "Solanum lycopersicum",
    category: "vegetable",
    location: "Plot 1",
    quantityAvailable: 26,
    unit: "pot",
    status: "available",
    tags: ["vegetable"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p10",
    scanCode: "PV-PLANT-0010",
    name: "Chili Plant",
    species: "Capsicum annuum",
    category: "vegetable",
    location: "Plot 1",
    quantityAvailable: 11,
    unit: "pot",
    status: "unavailable",
    tags: ["spicy"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p11",
    scanCode: "PV-PLANT-0011",
    name: "Neem Tree",
    species: "Azadirachta indica",
    category: "tree",
    location: "Orchard D",
    quantityAvailable: 7,
    unit: "tree",
    status: "available",
    tags: ["shade", "medicinal"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p12",
    scanCode: "PV-PLANT-0012",
    name: "Marigold Tray",
    species: "Tagetes",
    category: "flower",
    location: "Greenhouse 3",
    quantityAvailable: 30,
    unit: "seedling",
    status: "available",
    tags: ["seasonal", "bright"],
    createdAt: now,
    updatedAt: now,
  },
];
