import type { Reservation } from "@/types/reservation";

const now = new Date();
const toIso = (daysAgo: number) => new Date(now.getTime() - daysAgo * 86400000).toISOString();

export const reservationSeedData: Reservation[] = [
  {
    id: "r1",
    scanCode: "PV-RES-0001",
    plantId: "p1",
    plantName: "Alphonso Mango Tree",
    requestedQty: 2,
    requestedDate: new Date(now.getTime() + 5 * 86400000).toISOString(),
    userName: "Maya Patel",
    userId: "u1",
    status: "pending",
    createdAt: toIso(1),
  },
  {
    id: "r2",
    scanCode: "PV-RES-0002",
    plantId: "p2",
    plantName: "Kent Mango Sapling",
    requestedQty: 4,
    requestedDate: new Date(now.getTime() + 3 * 86400000).toISOString(),
    userName: "Liam Brooks",
    userId: "u2",
    status: "approved",
    createdAt: toIso(2),
  },
  {
    id: "r3",
    scanCode: "PV-RES-0003",
    plantId: "p6",
    plantName: "Rose Bush",
    requestedQty: 3,
    requestedDate: new Date(now.getTime() + 7 * 86400000).toISOString(),
    userName: "Maya Patel",
    userId: "u1",
    status: "rejected",
    createdAt: toIso(4),
  },
  {
    id: "r4",
    scanCode: "PV-RES-0004",
    plantId: "p9",
    plantName: "Tomato Plant",
    requestedQty: 5,
    requestedDate: new Date(now.getTime() + 4 * 86400000).toISOString(),
    userName: "Noah Kim",
    userId: "u3",
    status: "fulfilled",
    createdAt: toIso(6),
  },
  {
    id: "r5",
    scanCode: "PV-RES-0005",
    plantId: "p11",
    plantName: "Neem Tree",
    requestedQty: 1,
    requestedDate: new Date(now.getTime() + 9 * 86400000).toISOString(),
    userName: "Ava Chen",
    userId: "u4",
    status: "pending",
    createdAt: toIso(0),
  },
  {
    id: "r6",
    scanCode: "PV-RES-0006",
    plantId: "p8",
    plantName: "Basil Seedlings",
    requestedQty: 8,
    requestedDate: new Date(now.getTime() + 2 * 86400000).toISOString(),
    userName: "Maya Patel",
    userId: "u1",
    status: "approved",
    createdAt: toIso(3),
  },
];
